services:
  frontend:
    build:
        context: .
        dockerfile: Dockerfile
        target: prod
    restart: always
    container_name: frontend
    command: npm run dev
    ports:
        - "3000:3000"
    volumes:
      - .:/app
