services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    container_name: frontend-prod
    ports:
        - "8080:3000"

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    container_name: frontend-dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
