import Image from "next/image";
import { JSX } from "react";

const privacyPolicyContent = [
  {
    type: "h4",
    text: "Data protection",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `If possible, collecting personal data (like name, address or e-mail addresses) is always
    done on a voluntary basis. Using the services on this website is generally possible without
    giving personal data, if possible. Please be aware that data transfer in the internet (for
    example when communicating via e-mail) might have security holes. It is not possible to
    protect data completely against access through third parties. Third parties are hereby
    explicitly prohibited from using the contact data published within the scope of the imprint
    requirement to send promotional and informational materials that were not explicitly
    ordered.`,
  },
  {
    type: "h4",
    text: "Privacy Policy for Usage of Facebook - Plugins (Like-Button)",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `Our pages integrate plugins of the social network Facebook (Facebook Inc., 1601 Willow Road
    , Menlo Park, California, 94025 , United States) are integrated. The Facebook plugin, you
    agree to the Facebook logo or the "Like - Button" ("Like") on our side. You
    can find an overview of Facebook-plugins here: `,
    link: {
      href: "https://developers.facebook.com/docs/plugins/",
      text: "Facebook Social Plugins",
    },
  },
  {
    type: "p",
    text: `When you visit our pages, the plugin establishes a connection between your browser and the
    Facebook server is established. Facebook thereby obtains the information that you have with
    your IP Address for visiting our website. If you click on the Facebook "Like" button
    while you are logged into your Facebook account, you can link the content of our pages on
    your Facebook profile. Thereby Facebook can correlate your visit of our site with your user
    account. We point out that we as providers of the sites no knowledge of the content of the
    transmitted data and use them through Facebook. For more information, please refer to the
    privacy policy of Facebook at `,
    link: {
      href: "https://www.facebook.com/about/privacy",
      text: "Facebook's privacy policy",
    },
  },
  {
    type: "h4",
    text: "Privacy Statement for the Use of Google Analytics",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `This website uses Google Analytics, a web analytics service provided by Google Inc. 1600
    Amphitheatre Parkway Mountain View, CA 94043, USA. Google Analytics uses "cookies",
    text files that are stored on your computer, to help analyze how users use the website. The
    information generated by the cookie about your use of this website are usually transferred
    to a server of Google in the USA and stored there. In the case of activation of the IP
    anonymization on this website, your IP address will be truncated within Member states of the
    European Union or other parties to the Agreement on the European Economic Area. Only in
    exceptional cases the complete IP address is transmitted to a Google server in the USA and
    shortened there. On behalf of the operator of this website Google will use this information
    to evaluate your use of the website, compiling reports on website activity and providing
    other with website and internet related services to the website operator. Undertaken as part
    of Google Analytics that your IP address is not associated with any other data held by
    Google. You may refuse the use of cookies by selecting the appropriate settings on your
    browser, we would point out, however, that you may then be used to their full extent in this
    case not all features of this website. You can also prevent the collection of data generated
    by the cookie about your use of the website (including your IP address) to Google and the
    processing of these data by Google, by downloading available under the following link
    browser plugin and install: `,
    link: {
      href: "https://tools.google.com/dlpage/gaoptout?hl=en",
      text: "Google Analytics",
    },
  },
  {
    type: "h4",
    text: "Privacy Statement for using Google +1",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `The Google +1 button to publish information worldwide. about the Google +1 button lets you and other users personalized content from Google and our partners. 
    Google will store both the information that you have given for a content +1, as well as information about the page that you viewed when you click on +1. 
    Your +1' s can be shown as evidence along with your name and profile photo in Google services, such as in search results or in your Google profile, or elsewhere on websites and ads on the internet.
    Google records information about your +1- activities to improve Google's services for you and others. 
    In order to use the Google +1 button, you need a globally visible, public Google profile, which must contain at least the chosen name for the profile. 
    This name is used in all Google services. In some cases, this name can also substitute any other name that you used when sharing content under your Google account. 
    The identity of your Google profile can be shown to users who know your email address or other identifying information from you.`,
  },
  {
    type: "h4",
    text: "Privacy Statement for using Xing",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `Our website uses the functions of the XING network. 
    This is provided by XING AG, Dammtorstraße 29-32, 20354 Hamburg, Germany. 
    Every time you access one of our sites that contains Xing functions, a connection to Xing servers is established. 
    To the best of our knowledge, personal data is not stored as part of this process. 
    In particular, no IP addresses are stored, and user behaviour is not evaluated.
    You can find more information about data protection and the Xing “Share” button in Xing’s privacy statement: `,
    link: {
      href: "https://www.xing.com/app/share?op=data_protection",
      text: "Xing’s privacy statement",
    },
  },
  {
    type: "h4",
    text: "Information, deletion, storage",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `You have the right at any time to get free information about your stored personal data, 
    its origins and receivers, and the purpose of the data processing, as well as deleted. 
    To this end, or if you have other questions about personal data, you can turn to us at any time.`,
  },
  {
    type: "h4",
    text: "Cookies",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `These internet pages use cookies. Cookies do not damage your computer and do not contain viruses. 
    Cookies help make our services more user-friendly, more effective, and safer. 
    Cookies are small text files that are saved on your computer and stored in your browser. 
    Most of the cookies we use are called “session cookies”. They are automatically deleted after your visit ends. 
    Other cookies remain stored on your end device until you delete them. 
    These cookies enable us to recognise your browser when you make your next visit. 
    You can change your browser’s settings to inform you when cookies are set, to allow cookies only in individual cases, 
    to exclude the acceptance of cookies for certain cases, or in general, 
    as well as to activate the automatic deletion of cookies when the browser is closed. 
    If you deactivate cookies, you will restrict this website’s functionality.`,
  },
  {
    type: "h4",
    text: "Server-Log-Files",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `The provider of the sites automatically collects and stores information in what is known as “server log files”, 
    which your browser transmits to us automatically. These are: `,
    items: [
      "Browser type / Browser version",
      "Operating system used",
      "Referrer URL",
      "Host name of the accessing computer",
      "Time of the server request",
    ],
  },
  {
    type: "p",
    text: `These data are not assignable to specific people. 
    These data are not merged with other data sources. 
    We reserve the right to check these data afterwards, if we become aware of concrete indications of illegal use.`,
  },
  {
    type: "h4",
    text: "Contact form",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `If you send us inquiries by using the contact form, 
    we will store your data from the inquiry form, 
    including the contact data you have provided, 
    in order to process your request and in case you have follow-up questions. 
    We will not pass this information on without your consent.`,
  },
  {
    type: "h4",
    text: "Objection to promotional e-mails",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `It is hereby forbidden to use contact data published as part of the duty to provide 
    Legal Notice (Imprint) in order to send unsolicited advertisements or informative materials. 
    The site operators reserve the right to take legal action if unsolicited advertising information, 
    such as spam e-mails, is sent.`,
  },
  {
    type: "h4",
    text: "Information, correction, blocking and deletion",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `Personal data are only collected, processed, 
    used and stored so that they are inaccessible for third parties in order to respond to queries, 
    process agreements and for technical administration unless you have been 
    explicitly informed with regard to other purposes and you have consented to such use. 
    Data are disclosed to third parties only for the purpose of conclusion of contract and/or with your consent. 
    Personal data are neither disclosed nor sold. Consent to the use of data may be revoked at any time by double-D-IT. 
    You may request information about the stored data, the purpose of storage and their origin at any time. 
    Moreover, in accordance with statutory provisions you have a right to correction, blockage and deletion of personal data.`,
  },
  {
    type: "h4",
    text: "Security",
    className: "text-xl mt-12 border-b-2 border-b-green-200 text-center",
  },
  {
    type: "p",
    text: `Double-D-IT sets technical and organizational security 
    measures to ensure that your personal data is protected against loss, 
    incorrect adjustment or unauthorized access. 
    Exclusively authorized persons have access to your personal data only to serve the aforesaid`,
  },
];

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto mb-6">
      <div className="relative">
        <Image
          src="/double-d-it-office.png"
          alt="Double D IT Office image"
          className="opacity-40"
          width={2200}
          height={1000}
        />
        <h2 className="absolute inset-0 flex items-center justify-center">Privacy policy</h2>
      </div>

      {privacyPolicyContent.map((item, index) => {
        if (item.type === "p") {
          return (
            <div key={index}>
              <p>
                {item.text}
                {item.link && (
                  <a className="text-amber-200" href={item.link.href}>
                    {item.link.text}
                  </a>
                )}
              </p>
              {item.items && (
                <ul className="list-decimal list-inside">
                  {item.items.map((listItem, listIndex) => (
                    <li key={listIndex}>{listItem}</li>
                  ))}
                </ul>
              )}
            </div>
          );
        }

        const Tag = item.type as keyof JSX.IntrinsicElements;
        return (
          <Tag key={index} className={item.className}>
            {item.text}
          </Tag>
        );
      })}
    </div>
  );
};

export default PrivacyPolicy;
